import{u as t,p as e,c as n,L as o,h as i}from"./index.js";var r=Object.defineProperty,s=Object.getOwnPropertyDescriptor,a=(t,e,n,o)=>{for(var i,a=o>1?void 0:o?s(e,n):e,h=t.length-1;h>=0;h--)(i=t[h])&&(a=(o?i(e,n,a):i(a))||a);return o&&a&&r(e,n,a),a};let h=class extends o{constructor(){super(...arguments),this.imageUrl="https://via.placeholder.com/550",this.title="Title",this.content="lorem ipsum dolor sit amet consectetur"}render(){return i`
    <div id="top-card">
      <img 
        src=${this.imageUrl} 
        alt='picture related to ${this.title}'/>
    </div>
    <div id="bottom-card">
      <h1>${this.title}</h1>
      <p>${this.content}</p>
    </div>
    `}};h.styles=t('@import url("https://fonts.googleapis.com/css?family=Chivo:300,300i,400,400i,700,700i,900,900i|Saira+Extra+Condensed:100,200,300,400,500,600,700,800|Saira:100,200,300,400,500,600,700,800");\n:host {\n  transition: 1s;\n  transform: scale(1);\n  box-shadow: 0px 5px 10px 10px rgba(0, 0, 0, 0.1019607843);\n  display: flex;\n  flex-direction: column;\n  justify-content: space-around;\n  width: 15vw;\n  max-width: 15vw;\n  height: 17vw;\n  color: whitesmoke;\n}\n@media (max-width: 390px) {\n  :host {\n    width: 50vw;\n    max-width: 50vw;\n    height: 50vw;\n  }\n}\n:host #top-card {\n  border-radius: 15px 15px 0 0;\n  overflow: hidden;\n  background-color: #4F5384;\n  object-fit: cover;\n  height: 33.3333333333vw;\n  max-height: 33.3333333333vw;\n}\n:host #top-card img {\n  width: 100%;\n  height: 100%;\n  object-fit: cover;\n}\n:host #bottom-card {\n  background-color: #393C5C;\n  border-radius: 0 0 15px 15px;\n  overflow: hidden;\n  height: 16.6666666667vw;\n  max-height: 16.6666666667vw;\n  padding: 1em;\n  color: whitesmoke;\n}\n:host #bottom-card h1 {\n  font-size: 1.5em;\n  margin: 0;\n}\n:host #bottom-card p {\n  font-size: 1em;\n  margin: 0;\n}\n:host(:hover) {\n  box-shadow: 0 0 20px 0px rgba(0, 0, 0, 0.35);\n  transform: scale(1.1);\n}'),a([e({type:String})],h.prototype,"imageUrl",2),a([e({type:String})],h.prototype,"title",2),a([e({type:String})],h.prototype,"content",2),h=a([n("cei-card")],h),document.querySelector("#header").links=[{label:"Acceuil",urlLink:"#header"},{label:"Historique",urlLink:"./src/pages/historique.html"},{label:"Photos",urlLink:"./src/pages/photos.html"}];
